name: "weather_dbt"
version: "1.0.0"
profile: "weather_dbt"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  weather_dbt:
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table